-- oracle query: performance-p50-tool-latency
-- source tile: P50 Tool Latency (page: Latency)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 7 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production table SQL.
SELECT
  PERCENTILE_CONT(total_ms, 0.50) OVER () AS p50_tool_latency,
  PERCENTILE_CONT(total_ms, 0.75) OVER () AS p75_tool_latency,
  PERCENTILE_CONT(total_ms, 0.90) OVER () AS p90_tool_latency,
  PERCENTILE_CONT(total_ms, 0.99) OVER () AS p99_tool_latency
FROM (
  SELECT * FROM (
    SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id,
      JSON_VALUE(content, '$.tool') AS tool_name,
      CAST(JSON_VALUE(latency_ms, '$.total_ms') AS INT64) AS total_ms
    FROM `{{PROJECT}}.{{DATASET}}.{{TABLE}}`
    WHERE event_type = 'TOOL_COMPLETED'
  )
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
    AND (ARRAY_LENGTH(@filter_user_id) = 0 OR user_id IN UNNEST(@filter_user_id))
)
QUALIFY ROW_NUMBER() OVER () = 1
ORDER BY p50_tool_latency DESC, p75_tool_latency DESC, p90_tool_latency DESC, p99_tool_latency DESC
LIMIT 500
