-- oracle query: usage-top-5-users-with-most-traces
-- source tile: Top 5 users with most Traces (page: Agent & Sessions)
-- pinned block: fe6423cc9775b6dc61f7f7047dd4424603ddb3a1
-- dashboard date default: 14 days
-- call_row_policy: raw_row
-- GENERATED by oracle/gen_oracle.py — independent LookML
-- translation; must never share the production table SQL.
SELECT
  user_id AS user_id,
  COUNT(DISTINCT trace_id) AS total_traces
FROM (
  SELECT timestamp, event_type, agent, session_id, invocation_id, user_id, trace_id, span_id
  FROM `{{PROJECT}}.{{DATASET}}.{{TABLE}}`
  WHERE timestamp >= TIMESTAMP(@start_date, 'UTC')
    AND timestamp < TIMESTAMP(DATE_ADD(@end_date, INTERVAL 1 DAY), 'UTC')
    AND (ARRAY_LENGTH(@filter_agent) = 0 OR agent IN UNNEST(@filter_agent))
    AND (ARRAY_LENGTH(@filter_span_id) = 0 OR span_id IN UNNEST(@filter_span_id))
    AND (ARRAY_LENGTH(@filter_trace_id) = 0 OR trace_id IN UNNEST(@filter_trace_id))
)
GROUP BY user_id
ORDER BY total_traces DESC, user_id
LIMIT 5
