CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.agent_session` (agent_session_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.candidate` (candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.context_snapshot` (context_snapshot_id STRING, snapshot_payload STRING, snapshot_timestamp TIMESTAMP, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.decision_execution` (decision_execution_id STRING, business_entity_id STRING, latency_ms INT64, span_id STRING, trace_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.decision_point` (decision_point_id STRING, reversibility STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.selection_outcome` (selection_outcome_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.at_context_snapshot` (decision_execution_id STRING, context_snapshot_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.evaluates_candidate` (decision_point_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.executed_at_decision_point` (decision_execution_id STRING, decision_point_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.has_selection_outcome` (decision_execution_id STRING, selection_outcome_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.part_of_session` (decision_execution_id STRING, agent_session_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.rejected_candidate` (selection_outcome_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_7da57280.selected_candidate` (selection_outcome_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
