CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.agent_session` (agent_session_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.candidate` (candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.context_snapshot` (context_snapshot_id STRING, snapshot_payload STRING, snapshot_timestamp TIMESTAMP, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.decision_execution` (decision_execution_id STRING, business_entity_id STRING, latency_ms INT64, span_id STRING, trace_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.decision_point` (decision_point_id STRING, reversibility STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.selection_outcome` (selection_outcome_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.at_context_snapshot` (decision_execution_id STRING, context_snapshot_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.evaluates_candidate` (decision_point_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.executed_at_decision_point` (decision_execution_id STRING, decision_point_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.has_selection_outcome` (decision_execution_id STRING, selection_outcome_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.part_of_session` (decision_execution_id STRING, agent_session_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.rejected_candidate` (selection_outcome_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS `test-project-0728-467323.migration_v5_demo_56f9179f.selected_candidate` (selection_outcome_id STRING, candidate_id STRING, session_id STRING, extracted_at TIMESTAMP);
