#!/usr/bin/env python3
"""Render sql/*.sql.tmpl with the sentinel bindings.

Deterministic: same inputs must produce byte-identical output (CI asserts no
drift between the committed generated files and a fresh render).

Checks enforced:
  * every {{PLACEHOLDER}} in the template has a binding;
  * no placeholder survives rendering;
  * every sentinel value is unique and appears only where a placeholder was
    (count of occurrences == count of placeholder occurrences), so the
    Linking API string replacement can never corrupt unrelated identifiers.
"""

import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
PAIRS = [
    ("sql/events_v1.sql.tmpl", "sql/events_v1.template.sql"),
    ("sql/preflight.sql.tmpl", "sql/preflight.template.sql"),
]
PLACEHOLDER_RE = re.compile(r"\{\{([A-Z_]+)\}\}")


def render_text(template: str, values: dict[str, str], source: str) -> str:
  """Render one logical template, rejecting incomplete or colliding values."""
  if len(set(values.values())) != len(values):
    raise ValueError("sentinel values must be unique")

  names = set(PLACEHOLDER_RE.findall(template))
  missing = names - set(values)
  if missing:
    raise ValueError(f"{source}: unbound placeholders {sorted(missing)}")
  counts = {
      name: template.count("{{" + name + "}}") for name in names
  }
  rendered = template
  for name in names:
    rendered = rendered.replace("{{" + name + "}}", values[name])
  if PLACEHOLDER_RE.search(rendered):
    raise ValueError(f"{source}: unresolved placeholder after render")
  for name in names:
    if rendered.count(values[name]) != counts[name]:
      raise ValueError(
          f"{source}: sentinel {values[name]!r} collides with other text"
      )
  return (
      "-- GENERATED by tools/render_template.py from "
      f"{source} — do not hand-edit.\n"
      + rendered
  )


def main() -> int:
  bindings = yaml.safe_load(
      (ROOT / "bindings/template_bindings.yaml").read_text()
  )
  values = bindings["placeholders"]

  try:
    for src, dst in PAIRS:
      rendered = render_text((ROOT / src).read_text(), values, src)
      (ROOT / dst).write_text(rendered)
      print(f"rendered {dst}")
  except ValueError as exc:
    print(f"ERROR: {exc}", file=sys.stderr)
    return 1
  return 0


if __name__ == "__main__":
  sys.exit(main())
