#!/usr/bin/env python3
"""Render the public configurator's immutable report bindings and pages.

Outputs (both deterministic; ``--check`` verifies instead of writing):

* ``docs/report-config.mjs`` — one ``Object.freeze({...})`` JSON payload. The
  top level keeps the ADK bindings existing callers read; ``profiles`` holds
  one entry per dashboard surface (``adk`` from bindings/report_template.yaml
  + bindings/template_bindings.yaml, ``bqca`` from
  bindings/bqca_report_template.yaml + bindings/bqca_template_bindings.yaml).
* ``docs/bqca/index.html`` — the /bqca/ deep link: docs/index.html with the
  BQCA surface selected by default, page metadata for BQCA, and asset paths
  one level up. Every substitution must match an exact number of times, so
  an edit to docs/index.html that breaks the derivation fails loudly here.
"""

import argparse
import json
import pathlib
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONFIG_PATH = "docs/report-config.mjs"
INDEX_PATH = "docs/index.html"
BQCA_PAGE_PATH = "docs/bqca/index.html"
SITE_URL = "https://googlecloudplatform.github.io/BigQuery-Agent-Analytics-SDK/"

# ADK names that predate the profile split; they are not template metadata
# and stay fixed so the ADK Linking API URL is byte-identical to before.
ADK_LABEL = "ADK Agents"
ADK_DATASOURCE_NAME = "BQAA"
ADK_DEFAULT_TABLE = "agent_events"
BQCA_LABEL = "BQCA Prompt & Response Logging"

BQCA_TITLE = "Configure BQCA Prompt &amp; Response Logging"
BQCA_DESCRIPTION = (
    "Create a private Looker Studio dashboard from your BigQuery"
    " Conversational Analytics Prompt &amp; Response Logging table."
)
BQCA_SHORT_DESCRIPTION = (
    "Create a private Looker Studio dashboard from your BQCA Prompt &amp;"
    " Response Logging table."
)
GENERATED_MARKER = (
    "<!-- Generated by tools/render_web_config.py from docs/index.html;"
    " do not edit. -->"
)


def load_mapping(path: pathlib.Path) -> dict:
  value = yaml.safe_load(path.read_text())
  if not isinstance(value, dict):
    raise ValueError(f"{path}: expected a mapping")
  return value


def load_sentinels(path: pathlib.Path) -> dict:
  placeholders = load_mapping(path).get("placeholders")
  if not isinstance(placeholders, dict):
    raise ValueError(f"{path.name}: placeholders must be a mapping")
  return {
      "project": placeholders["PROJECT"],
      "dataset": placeholders["DATASET"],
      "table": placeholders["TABLE"],
  }


def build_config() -> dict:
  """Return the REPORT_CONFIG payload for docs/report-config.mjs."""
  report = load_mapping(ROOT / "bindings/report_template.yaml")
  sentinels = load_sentinels(ROOT / "bindings/template_bindings.yaml")
  bqca = load_mapping(ROOT / "bindings/bqca_report_template.yaml")
  bqca_sentinels = load_sentinels(ROOT / "bindings/bqca_template_bindings.yaml")

  adk_profile = {
      "id": "adk",
      "label": ADK_LABEL,
      "reportId": report["report_id"],
      "dataSourceAlias": report["data_source_alias"],
      "sentinels": sentinels,
      "defaultTable": ADK_DEFAULT_TABLE,
      "reportName": report["default_report_name"],
      "datasourceName": ADK_DATASOURCE_NAME,
  }
  bqca_profile = {
      "id": "bqca",
      "label": BQCA_LABEL,
      "reportId": bqca["report_id"],
      "dataSourceAlias": bqca["data_source_alias"],
      "sentinels": bqca_sentinels,
      "defaultTable": bqca["default_table"],
      "reportName": bqca["default_report_name"],
      "datasourceName": bqca["datasource_name_prefix"],
  }
  return {
      "reportId": adk_profile["reportId"],
      "dataSourceAlias": adk_profile["dataSourceAlias"],
      "sentinels": sentinels,
      "defaultTable": ADK_DEFAULT_TABLE,
      "profiles": {"adk": adk_profile, "bqca": bqca_profile},
  }


def render_config() -> str:
  config = build_config()
  return (
      "// Generated by tools/render_web_config.py; do not edit.\n"
      "export const REPORT_CONFIG ="
      f" Object.freeze({json.dumps(config, indent=2)});\n"
  )


def _replace(text: str, old: str, new: str, count: int) -> str:
  found = text.count(old)
  if found != count:
    raise ValueError(
        f"{INDEX_PATH}: expected {count} occurrence(s) of {old!r}, found"
        f" {found}; update tools/render_web_config.py with the page"
    )
  return text.replace(old, new)


def render_bqca_page(index_html: str) -> str:
  """Derive the /bqca/ page from docs/index.html."""
  page = index_html
  page = _replace(
      page, "<!doctype html>\n", f"<!doctype html>\n{GENERATED_MARKER}\n", 1
  )
  page = _replace(
      page,
      '<html lang="en">',
      '<html lang="en" data-bqca-default-profile="bqca">',
      1,
  )
  for asset in ('href="./favicon.svg"', 'href="./styles.css"'):
    page = _replace(page, asset, asset.replace("./", "../"), 1)
  page = _replace(page, 'src="./app.mjs"', 'src="../app.mjs"', 1)
  # og:url and the canonical link name the deep link itself.
  page = _replace(page, f'"{SITE_URL}"', f'"{SITE_URL}bqca/"', 2)
  page = _replace(page, "Configure BigQuery Agent Analytics", BQCA_TITLE, 3)
  page = _replace(
      page,
      "Create a private Looker Studio dashboard from your BigQuery Agent"
      " Analytics installation.",
      BQCA_DESCRIPTION,
      1,
  )
  page = _replace(
      page,
      "Create a private Looker Studio dashboard from your BQAA event table.",
      BQCA_SHORT_DESCRIPTION,
      2,
  )
  # Select the BQCA surface: pressed state and profile-only copy flip, so the
  # page is correct before app.mjs runs (and its runtime state agrees).
  page = _replace(
      page,
      'id="profile-adk" aria-pressed="true"',
      'id="profile-adk" aria-pressed="false"',
      1,
  )
  page = _replace(
      page,
      'id="profile-bqca" aria-pressed="false"',
      'id="profile-bqca" aria-pressed="true"',
      1,
  )
  # The table-ID placeholder names the surface's default table, exactly as
  # app.mjs writes it at runtime.
  bqca_table = load_mapping(ROOT / "bindings/bqca_report_template.yaml")[
      "default_table"
  ]
  page = _replace(
      page,
      f'placeholder="my-project.my_dataset.{ADK_DEFAULT_TABLE}"',
      f'placeholder="my-project.my_dataset.{bqca_table}"',
      1,
  )
  adk_only = 'data-profile-only="adk">'
  bqca_only = 'data-profile-only="bqca" hidden>'
  adk_count = page.count(adk_only)
  bqca_count = page.count(bqca_only)
  if not adk_count or not bqca_count:
    raise ValueError(
        f"{INDEX_PATH}: expected ADK-visible and BQCA-hidden profile-only"
        f" elements (adk={adk_count}, bqca={bqca_count})"
    )
  if page.count('data-profile-only="') != adk_count + bqca_count:
    raise ValueError(
        f"{INDEX_PATH}: profile-only elements must end with"
        f" {adk_only!r} or {bqca_only!r}"
    )
  page = page.replace(adk_only, "\0ADK\0").replace(bqca_only, "\0BQCA\0")
  page = page.replace("\0ADK\0", 'data-profile-only="adk" hidden>')
  page = page.replace("\0BQCA\0", 'data-profile-only="bqca">')
  return page


def outputs(profile: str = "all") -> dict[str, str]:
  rendered = {
      CONFIG_PATH: render_config(),
      BQCA_PAGE_PATH: render_bqca_page((ROOT / INDEX_PATH).read_text()),
  }
  if profile == "adk":
    return {CONFIG_PATH: rendered[CONFIG_PATH]}
  if profile in ("bqca", "all"):
    return rendered
  raise ValueError(f"unknown profile {profile!r}")


def main(argv: list[str] | None = None) -> int:
  parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
  parser.add_argument(
      "--profile",
      choices=("adk", "bqca", "all"),
      default="all",
      help="dashboard profile to render or check (default: all)",
  )
  parser.add_argument(
      "--check",
      action="store_true",
      help="compare with the committed files instead of writing them",
  )
  args = parser.parse_args(argv)
  try:
    rendered = outputs(args.profile)
  except (KeyError, ValueError) as exc:
    print(f"ERROR: {exc}", file=sys.stderr)
    return 1
  stale = []
  for relative, text in rendered.items():
    path = ROOT / relative
    if args.check:
      if not path.exists() or path.read_text() != text:
        stale.append(relative)
      continue
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"rendered {relative}")
  for relative in stale:
    print(f"DRIFT: {relative} is stale; rerun without --check", file=sys.stderr)
  if args.check and not stale:
    print("ok: web configuration matches its sources")
  return 1 if stale else 0


if __name__ == "__main__":
  raise SystemExit(main())
