#!/usr/bin/env python3
"""Render sql/*.sql.tmpl with the sentinel bindings of each profile.

Profiles:
  * adk  — sql/events_v1 + sql/preflight with bindings/template_bindings.yaml
  * bqca — sql/bqca_events_v1 + sql/bqca_preflight with
           bindings/bqca_template_bindings.yaml

Deterministic: same inputs must produce byte-identical output (CI asserts no
drift between the committed generated files and a fresh render). By default
every profile is rendered; ``--check`` compares instead of writing and exits
non-zero on drift.

Checks enforced:
  * every {{PLACEHOLDER}} in the template has a binding;
  * no placeholder survives rendering;
  * every sentinel value is unique and appears only where a placeholder was
    (count of occurrences == count of placeholder occurrences), so the
    Linking API string replacement can never corrupt unrelated identifiers.
"""

import argparse
import pathlib
import re
import sys

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROFILES = {
    "adk": {
        "bindings": "bindings/template_bindings.yaml",
        "pairs": [
            ("sql/events_v1.sql.tmpl", "sql/events_v1.template.sql"),
            ("sql/preflight.sql.tmpl", "sql/preflight.template.sql"),
        ],
    },
    "bqca": {
        "bindings": "bindings/bqca_template_bindings.yaml",
        "pairs": [
            ("sql/bqca_events_v1.sql.tmpl", "sql/bqca_events_v1.template.sql"),
            ("sql/bqca_preflight.sql.tmpl", "sql/bqca_preflight.template.sql"),
        ],
    },
}
# The ADK pairs, kept under their original name for existing callers.
PAIRS = PROFILES["adk"]["pairs"]
PLACEHOLDER_RE = re.compile(r"\{\{([A-Z_]+)\}\}")


def render_text(template: str, values: dict[str, str], source: str) -> str:
  """Render one logical template, rejecting incomplete or colliding values."""
  if len(set(values.values())) != len(values):
    raise ValueError("sentinel values must be unique")

  names = set(PLACEHOLDER_RE.findall(template))
  missing = names - set(values)
  if missing:
    raise ValueError(f"{source}: unbound placeholders {sorted(missing)}")
  counts = {name: template.count("{{" + name + "}}") for name in names}
  rendered = template
  for name in names:
    rendered = rendered.replace("{{" + name + "}}", values[name])
  if PLACEHOLDER_RE.search(rendered):
    raise ValueError(f"{source}: unresolved placeholder after render")
  for name in names:
    if rendered.count(values[name]) != counts[name]:
      raise ValueError(
          f"{source}: sentinel {values[name]!r} collides with other text"
      )
  return (
      "-- GENERATED by tools/render_template.py from "
      f"{source} — do not hand-edit.\n" + rendered
  )


def load_placeholders(profile: str) -> dict[str, str]:
  """Return the sentinel placeholders bound for one profile."""
  path = ROOT / PROFILES[profile]["bindings"]
  bindings = yaml.safe_load(path.read_text())
  values = bindings.get("placeholders") if isinstance(bindings, dict) else None
  if not isinstance(values, dict):
    raise ValueError(f"{path.name}: placeholders must be a mapping")
  return values


def render_profile(profile: str) -> dict[str, str]:
  """Return {output path: rendered text} for every pair of one profile."""
  values = load_placeholders(profile)
  return {
      dst: render_text((ROOT / src).read_text(), values, src)
      for src, dst in PROFILES[profile]["pairs"]
  }


def main(argv: list[str] | None = None) -> int:
  parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
  parser.add_argument(
      "--profile",
      choices=(*PROFILES, "all"),
      default="all",
      help="profile to render (default: all)",
  )
  parser.add_argument(
      "--check",
      action="store_true",
      help="compare with the committed files instead of writing them",
  )
  args = parser.parse_args(argv)
  profiles = list(PROFILES) if args.profile == "all" else [args.profile]

  stale = []
  try:
    for profile in profiles:
      for dst, rendered in render_profile(profile).items():
        path = ROOT / dst
        if args.check:
          current = path.read_text() if path.exists() else None
          if current != rendered:
            stale.append(dst)
          continue
        path.write_text(rendered)
        print(f"rendered {dst}")
  except ValueError as exc:
    print(f"ERROR: {exc}", file=sys.stderr)
    return 1
  if stale:
    for dst in stale:
      print(f"DRIFT: {dst} is stale; rerun without --check", file=sys.stderr)
    return 1
  if args.check:
    print(f"ok: {', '.join(profiles)} templates match their sources")
  return 0


if __name__ == "__main__":
  sys.exit(main())
